global using AlexeyRomero_Tarea1_PrograAvanzada.Models;
global using AlexeyRomero_Tarea1_PrograAvanzada.Data;
global using AlexeyRomero_Tarea1_PrograAvanzada.Services;
global using Microsoft.AspNetCore.Mvc;
global using System.Diagnostics;
global using System.Linq;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using X.PagedList;